- type: job
  id: Blueshield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueshield
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 3600
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600
    - !type:OverallPlaytimeRequirement
      time: 108000
  weight: 10
  startingGear: BlueshieldGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - Security
  - Service
  - Medical
  - Brig
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueshieldGear
  equipment:
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesGlassesBlueshield
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponDisabler
    id: BlueshieldPDA
    ears: ClothingHeadsetAltBlueshield
    shoes: ClothingShoesBootsCombatFilled
